- hosts: localhost
  tasks:
    - name: Update Staging Sites
      command: flock /tmp/bench.lock -c "bench update"
      args:
        chdir: /home/frappe/frappe-bench
    - name: Update Demo Sites
      command: flock /tmp/bench.lock -c "bench update"
      args:
        chdir: /home/frappe/frappe-demo
